name: Jest Tests

on:
  push:
    branches:
      - 'main'

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Jest tests
        id: jest
        run: |
          set +e
          npm test -- --json --outputFile=jest-results.json
          
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          set -e

      - name: Read Jest results
        id: results
        run: |
          RESULTS=$(cat jest-results.json | jq -r '.testResults[].status' | sort | uniq -c)
          echo "summary=$RESULTS" >> $GITHUB_OUTPUT

      # Post results to workflow summary
      - name: Post Jest Results
        id: jestOutput
        run: |
          echo "## Jest Test Results" >> $GITHUB_STEP_SUMMARY
          cat jest-results.json | jq '.testResults[] | "\(.name): \(.status)"' >> $GITHUB_STEP_SUMMARY
          # echo "jesty=" & $GITHUB_STEP_SUMMARY
          echo "jesty=Hello from Job 1" >> $GITHUB_OUTPUT

      - name: Send discord notification
        if: always()
        run: |
          STATUS="✅ UnitTests passed"
          if [ "${{ steps.jest.outputs.exit_code }}" != "0" ]; then
            STATUS="❌ UnitTests failed"
          fi

          MESSAGE="${STATUS} on branch **${GITHUB_REF_NAME}**.\n\nResults:\n${{ steps.results.outputs.summary }}"

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"${MESSAGE}\"}" \
            ${{ secrets.WEBHOOK_URL }}

